services:
  postgres:
    image: postgres:15-alpine
    container_name: lapcw-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-auth_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/db-init:/docker-entrypoint-initdb.d
    networks:
      - lapcw-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d auth_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:6.0
    container_name: lapcw-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - lapcw-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: lapcw-rabbitmq
    restart: always
    ports:
      - "5672:5672"   # Protocol AMQP
      - "15672:15672" # Management UI
      - "15692:15692" # Prometheus Metrics
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-guest}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - lapcw-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3

  minio:
    image: minio/minio
    container_name: lapcw-minio
    restart: always
    ports:
      - "9000:9000" # API Port
      - "9001:9001" # Console UI Port
    environment:
      MINIO_ROOT_USER: ${MINIO_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD:-minioadmin}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - lapcw-network

  prometheus:
    image: prom/prometheus
    container_name: lapcw-prometheus
    restart: always
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - lapcw-network

  grafana:
    image: grafana/grafana
    container_name: lapcw-grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - lapcw-network

  gateway:
    image: nginx:alpine
    container_name: lapcw-gateway
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - postgres
      - mongo
    networks:
      - lapcw-network

networks:
  lapcw-network:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
  rabbitmq_data:
  minio_data:
  grafana_data: