services:
  postgres:
    image: postgres:15-alpine
    container_name: lapcw-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: report_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lapcw-network

  mongo:
    image: mongo:6.0
    container_name: lapcw-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - lapcw-network

  minio:
    image: minio/minio
    container_name: lapcw-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - lapcw-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: lapcw-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - lapcw-network

  gateway:
    image: nginx:alpine
    container_name: lapcw-gateway
    ports:
      - "8080:80"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service
      - report-service
    networks:
      - lapcw-network

  prometheus:
    image: prom/prometheus
    container_name: lapcw-prometheus
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - lapcw-network

  grafana:
    image: grafana/grafana
    container_name: lapcw-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - lapcw-network

  auth-service:
    build: ./services/auth-service
    environment:
      - DB_HOST=postgres
      - JWT_SECRET=rahasia_negara
    networks:
      - lapcw-network

networks:
  lapcw-network:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
  minio_data: