global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Monitoring RabbitMQ
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['lapcw-rabbitmq:15692']
  
  # Monitoring Backend Services
  - job_name: 'auth-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['auth-service:8081']

  - job_name: 'report-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['report-service:8082']

  - job_name: 'notification-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['notification-service:8084']

  # Monitoring Nginx Gateway
  - job_name: 'nginx-gateway'
    metrics_path: '/gateway/metrics'
    static_configs:
      - targets: ['gateway:80']
